# Generated by Django 5.1.6 on 2025-04-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prediction_period', models.CharField(choices=[('1month', '1 Month'), ('3month', '3 Months'), ('6month', '6 Months')], max_length=20)),
                ('chart_image', models.ImageField(upload_to='charts/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
